spring.application.name=rabbitMQPractice
rabbitmq.queue.name=myQueue1
rabbitmq.exchange.name=myExchange1
rabbitmq.routingkey.name=myRoutingKey
rabbitmq.json.queue.name=myQueue2
rabbitmq.json.routingkey.name=myRoutingKey2